backend:
  name: github
  # change repo to your git repository url
  repo: melvinisican/mji-dev-showcase

media_folder: static/assets
public_folder: /assets

collections:
  - name: settings
    label: Settings
    files:
      - name: config
        label: Config
        file: site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Site Title
            required: true
          - widget: string
            name: siteUrl
            label: Website URL
            required: true
          - widget: text
            name: description
            label: Description
            default: ''
            required: false
          - widget: object
            name: home
            label: Homepage Options
            fields:
              - widget: string
                name: title
                label: Title
                default: ''
                required: false
              - widget: markdown
                name: description
                label: Description
                default: ''
                required: false
  - name: 'pages'
    label: 'Pages'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: 'content/pages/about.md'
        label: 'About Page'
        name: 'about-page'
        fields:
          - {
            label: Template,
            name: template,
            widget: hidden,
            default: AboutPage,
          }
          - { label: Slug, name: slug, widget: hidden, default: 'components' }
          - { label: Title, name: title, widget: string }
          - { label: Featured Images, name: featuredImage, widget: image }
          - { label: Subtitle, name: subtitle, widget: markdown, required: false }
          - { label: Section 1, name: section1, widget: markdown, required: false }
          - { label: Section 2, name: section2, widget: markdown, required: false }
          - { name: video, label: video, widget: file, required: false }
          - { name: videoPoster, label: videoPoster, widget: image, required: false }
          - { label: videoTitle, name: videoTitle, widget: string, required: false }
          - label: 'accordion'
            name: 'accordion'
            widget: 'list'
            fields:
              - { name: title, label: title, widget: string, default: '' }
              - { name: description, label: description, widget: string }
          - label: 'Gallery'
            name: 'gallery'
            widget: 'list'
            fields:
              - { name: image, label: Image, widget: image }
              - { name: alt, label: Alt, widget: string }
              - { name: title, label: Title, widget: string, required: false }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                label: Description,
                name: description,
                widget: text,
                required: false,
              }
              - {
                label: Canonical Link,
                name: canonicalLink,
                widget: string,
                required: false,
              }
              - {
                label: Noindex,
                name: noindex,
                widget: boolean,
                required: false,
              }
  - name: blog
    label: Blog
    folder: _data/blog
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: BlogPost,
        }
      - name: path
        label: Path
        widget: string
        pattern: [/]
        hint: "Path must start with /"
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
